### ISSUE TITLE
任务八、css常见样式

### ISSUE THREAD

**Issue by rabbit-tian** [rabbit-tian/blog#16]
## 任务八、css常见样式

1. 块级元素和行内元素分别有哪些？动手测试并列出4条以上的特性区别

   - **块级元素：** div h1 h2 h3 h4 h5 h6 p hr form ul dl ol pre table li dd dt tr td th
   - **行内元素**：em strong span a br img button iput label select textarea code script  

   区别：

   - 块级元素：display：block ，会独占一行，默认情况下会填满父元素宽度；可以设置宽高；可以设置margin和padding；
   - 行内元素：display： inline，不会独占一行，相邻的元素会排在一行，其宽度随内容的变化而变化；不可以设置宽高；可以设置左右方向的margin和padding，上下无效；

2. 什么是 CSS 继承? 哪些属性能继承，哪些不能？

   - css继承：子标签继承了上级标签的CSS样式的属性
   - 不可继承的：display、margin、border、padding、background、height、min-height、max-
      height、width、min-width、max-width、overflow、position、left、right、top、bottom、z-
      index、float、clear、table-layout、vertical-align、page-break-after、page-bread-before和
      unicode-bidi。
   - 所有元素可继承：visibility和cursor。
   - 内联元素可继承：letter-spacing、word-spacing、white-space、line-height、color、font、font-
      family、font-size、font-style、font-variant、font-weight、text-decoration、text-transform、
      direction。
   - 终端块状元素可继承：text-indent和text-align。
   - 列表元素可继承：list-style、list-style-type、list-style-position、list-style-image。
   - 表格元素可继承：border-collapse。

3. 如何让块级元素水平居中？如何让行内元素水平居中?

   1. 块级元素水平居中：margin：0 auto；
   2. 行内元素水平居中：text-align：center；

4. 用 CSS 实现一个三角形

   ```css
   .tri{
     width:0;
     height:0;
     border-style:solid;
     border-width:0 100px 100px 100px;
     border-color:transparent red transparent transparent;
   }
   ```

5. 单行文本溢出加 `...`如何实现?

   ```css
   .box h3{
     padding:0 20px;
     white-space: nowrap;
     overflow: hidden;
     text-overflow: ellipsis;
   }
   ```

6. px, em, rem 有什么区别

   - px： 固定单位，多少个像素 
   - em: 相对单位，相对于父元素字体大小 
   - rem: 相对单位，相对于根元素(html)字体大小 

7. 解释下面代码的作用?为什么要加引号? 字体里`\5b8b\4f53`代表什么?

   ```css
   body{
     font: 12px/1.5 tahoma,arial,'Hiragino Sans GB','\5b8b\4f53',sans-serif;
   }
   ```

   1. 代码作用
      - 该段代码设置了body的font样式，字体大小为12px，行高是字体1.5倍的像素值，后面则是第一到第五字体，用逗号隔开，如果用户浏览第一字体没有，则查询第二字体有没有，以此类推，如果都没有则采用系统默认字体；
      - 字体为什么要加引号? 
        因为采用中文或者英文字体有空格时，不加引号可能导致用户浏览器不能识别字体，产生乱码； 
        字体里的数字符号代表什么? 
        代表字体的Unicod码，Unicode码全球通用，用该码表示字体是最保险的，获得该码的方式可以在网上查找，或者在开发者工具中输入escape指令 
        ![img](https://leanote.com/api/file/getImage?fileId=590d8ce6ab64416a62002daf)
