### ISSUE TITLE
任务十二、浏览器兼容

### ISSUE THREAD

**Issue by rabbit-tian** [rabbit-tian/blog#19]
## 任务十二、浏览器兼容

1. 什么是 CSS hack

   CSS hack由于不同厂商的[浏览器](http://baike.baidu.com/item/%E6%B5%8F%E8%A7%88%E5%99%A8)，比如Internet Explorer,Safari,[Mozilla Firefox](http://baike.baidu.com/item/Mozilla%20Firefox),Chrome等，或者是同一厂商的浏览器的不同版本，如IE6和IE7，对CSS的解析认识不完全一样，因此会导致生成的页面效果不一样，得不到我们所需要的页面效果。 这个时候我们就需要针对不同的浏览器去写不同的CSS，让它能够同时兼容不同的浏览器，能在不同的浏览器中也能得到我们想要的页面效果。

   简单的说，CSS hack的目的就是使你的CSS代码兼容不同的浏览器。当然，我们也可以反过来利用CSS hack为不同版本的浏览器定制编写不同的CSS效果。

   CSS Hack大致有三种表现形式，CSS属性前缀法，选择器前缀法以及IE条件注释法（即HTML头部引用 if IE）hack，实际项目中CSS Hack大部分是针对IE浏览器不同版本之间的表现差异而引入的。

2. 谈一谈浏览器兼容的思路

 - 要不要做：
     - 产品的角度（产品的受众、受众的浏览器比例、效果优先还是基本功能优先）
     - 成本的角度 (有无必要做某件事)

- 要做到什么程度:
     - 让哪些浏览器支持哪些效果,根据浏览器的支持情况去做
- 如何做：
     - 根据兼容需求选择技术框架/库(jquery)
     - 根据兼容需求选择兼容工具([html5shiv.js](https://github.com/aFarkas/html5shiv)、[respond.js](https://github.com/scottjehl/Respond)、[css reset](https://segmentfault.com/a/1190000003021766)、[normalize.css](https://github.com/necolas/normalize.css)、[Modernizr](https://github.com/Modernizr/Modernizr))
     - [postCSS](https://github.com/postcss/postcss)
     - 条件注释、CSS Hack、js 能力检测做一些修补

3. 列举5种以上浏览器兼容的写法

   1. 条件注释

      ```css
      <!--[if IE 6]> <p>You are using Internet Explorer 6.</p> 
      <![endif]-->  在IE6下出现p标签
      <!--[if !IE]><!-->  在IE下不显示，在非IE下弹出1；
      <script>alert(1);</script>
      <!--<![endif]-->
      <!--[if IE 8]>  在IE6下引入css文件
      <link href="ie8only.css" rel="stylesheet"> 
      <![endif]-->
      ```

   2. 属性前缀

      ```css
      .box{ 
          color: red; 
        	_color: blue; /*ie6*/
          *color: pink; /*ie67*/ 
          color: yellow\9; /*ie/edge 6-8*/
      }
      ```

   3. 清浮动

      ```css
      .clearfix:after{
        content: "";
        display: block;
        clear: both:
      }
      .clearfix{
        *zoom: 1;   触发BFC，针对IE6，7
      }
      ```

   4. inline-block

      ```css
      .target{
        display: inline-block;
        *display: inline;
        *zoom: 1;
      }
      ```

   5. 利用html5shiv、respond

      ```css
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      ```

4. 以下工具/名词是做什么的

   - 条件注释

     条件注释是于HTML源码中被IE有条件解释的语句。条件注释可被用来向IE提供及隐藏代码。

   - IE Hack

     针对IE浏览器编写不同的CSS让IE能够正常渲染。

   - js 能力检测

     浏览器的能力检测目标不是检测特定的浏览器，而是检测浏览器的能力。这样，只需要检测浏览器是否支持特定的能力，就可以给出特定的解决方案。这一部分检测是解决浏览器兼容问题的主要检测。

   - html5shiv.js

     解决ie9以下版本的浏览器对html5标签无法识别的问题。

   - respond.js

     提供一个小脚本，以便在不支持CSS3媒体查询的浏览器中启用响应式网页设计，特别是ie8及更低版本。

   - css reset

     重置浏览器默认样式。

   - normalize.css

     Normalize.css 是一个可以定制的CSS文件，它让不同的浏览器在渲染网页元素的时候形式更统一。

   - Modernizr

     Modernizr是一套JavaScript 库，用来侦测浏览器是否支持HTML5与CSS3等规格。如果浏览器不支持，Modernizr会使用其他的解决方法来进行模拟。

   - postCSS

     PostCSS是一个JS插件转换样式表的工具。这些插件能够检验你的CSS、支持变量和混合，转化css3的新特性语法、行内图片等。

5. 一般在哪个网站查询属性兼容性？

   - [浏览器市场份额](http://tongji.baidu.com/data/browser)
   - [caniuse.com](http://caniuse.com/) 查CSS属性兼容
   - [browserhacks](http://browserhacks.com/) 查 Hack 的写法
