### ISSUE TITLE
两栏布局和三栏布局

### ISSUE THREAD

**Issue by rabbit-tian** [rabbit-tian/blog#20]
## 面试题9、多栏布局

  两栏布局

         1. **方法一：浮动布局**

            要点：左边浮动，右边加上一个margin-left值，让他实现左边固定，右边自适应的布局效果

         ```css
         <style>
             .side{
                 float: left;
                 width: 200px;
                 height: 200px;
                 background-color: pink;
             }
             .main{
                 height: 200px;
                 background: red;
                 margin-left: 200px;
             }
         </style>
         </head>
         <body>
             <div class="side">side</div>
             <div class="main">main</div>
         </body>
         ```

         2. ##### 方法二：BFC布局

            要点：将侧边区块side浮动，side浮动后覆盖main区域, 再将main设置overflow:hidden，形成BFC，形成独立区域

            ```css
            <style>
            .side{
                width: 200px;
                height: 400px;
                float: left;
                background-color: pink;
            }
            .main{
                height: 600px;
                background: red;
                overflow: hidden; /* 形成BFC */
            }
            </style>
            </head>
            <body>
                <div class="side">side</div>
                <div class="main">main</div>
            </body>
            ```

         3. ##### 方法三：flex布局

            要点：父盒子设置display:flex（弹性盒模型），左侧side设置固宽，main设置

         ​       flex-grow: 1;（main自动填补剩余宽度）

         ​	

         ```css
         <style media="screen">
         #box{
             display: flex;
         }
         .side{
             width: 200px;
             background-color: pink;
         }
         .main{
             background: red;
             flex-grow: 1;
         }
         </style>
         </head>
         <body>
             <div id="box">
                 <div class="side">side</div>
                 <div class="main">main</div>
             </div>
         </body>
         ```

         4. ##### 方法四：display：table-cell 布局

            ```css
            <style>
            #box{
                display: table;
                width: 100%;
            }
            .side{
                display: table-cell;
                width: 200px;
                background-color: pink;
            }
            .main{
                display: table-cell;
                background-color: red;
            }
            </style>
            </head>
            <body>
                <div id="box">
                    <div class="side">side</div>
                    <div class="main">main</div>
                </div>
            </body>
            ```

         5. ##### 方法五：负margin值布局

            ```css
            <style>
            .clearfix:after{
                content:'';
                display: block;
                clear:both;
                height: 0;
                visibility: hidden;
            }
            .main-wrap{
                width: 100%;
                float: left;
            }
            .side{
                width: 200px;
                float: left;
                background-color: pink;
                /*此时side移动到main-wrap的左侧，且覆盖在其身上*/
                margin-left: -100%;
            }
            .main{
                background-color: red;
                /* 留出side的宽度 */
                margin-left: 200px;
            }
            </style>
            </head>
            <body>
                <div class="wrap clearfix">
                    <div class="main-wrap">
                        <div class="main">main</div>
                    </div>
                    <div class="side">side</div>
                </div>
            </body>
            ```

  三栏布局

         1. ##### 方法一：绝对定位法

            要点：左右两栏采用绝对定位，分别固定于页面的左右两侧，中间的主体栏用左右margin值撑开距离

            ```css
            <style>
            html,body{margin: 0;}
            .left{
                position: absolute;
                top: 0;
                left: 0;
                background-color: pink;
                width: 200px;
            }
            .right{
                position: absolute;
                top: 0;
                right: 0;
                background-color: yellow;
                width: 200px;
            }
            .main{
                margin: 0 210px;
                background-color: red;
            }

            </style>
            </head>
            <body>
            <div class="left">left</div>
            <div class="main">main</div>
            <div class="right">right</div>
            </body>
            ```

         2. ##### 方法二：浮动布局

            要点：左右两栏采用左右浮动，分别于页面的左右两侧，中间的主体栏用左右margin值撑开距离

            ```css
            <style>
                #content:after{
                    content:"";
                    display: block;
                    clear: both;
                }
                .aside{
                    width: 150px;
                    height:300px;
                    background-color: red;
                    float:left;
                }
                .extra{
                    width: 150px;
                    height:300px;
                    background-color: blue;
                    float: right;
                }
                .main{
                    margin: 0 160px;
                    height: 500px;
                    background-color: pink;
                }
                .footer{
                    background-color: green;
                }
            </style>
            </head>
            <body>
                <div id="content">
                    <div class="aside">aside</div>
                    <div class="extra">extra</div>
                    <div class="main"></div>
                </div>
                <div class="footer">footer</div>
            </body>
            ```

         3. 方法三：双飞翼布局（margin负值）

            ```css
            #content:after{
                content:"";
                display: block;
                clear:both;
            }
            .aside{
                float:left;
                width: 100px;
                height: 300px;
                background-color: red;
              /* aside先margin负值移动到wrap的右侧覆盖在其上*/
                margin-left: -100%;
            }
            .extra{
                float:left;
                width: 150px;
                height: 300px;
                background-color: yellow;
              /* extra再margin负值本身的距离到wrap的左侧覆盖在其上*/
                margin-left: -150px;
            }
            .wrap{
                width: 100%;
                float:left;
            }
            .main{
                height: 400px;
                background-color: blue;
              /* main左右margin，让出左右侧元素的宽度 */
                margin-left: 100px;
                margin-right: 150px;
            }

            <body>
                <div id="content">
                    <div class="wrap">
                        <div class="main">main</div>
                    </div>
                    <div class="aside">aside</div>
                    <div class="extra">extra</div>
                </div>
            </body>
            ```
